---
title: "Capstone 1"
team name: "Group 0"
author: "Spencer Fogelman, Rayn Goodwin, Queena Wang"
date: "2/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Question 1

```{r}
breweries = read.csv('/Users/spencerfogelman/Downloads/CaseStudy1_2_2/Breweries.csv', stringsAsFactors = FALSE)
beers = read.csv('/Users/spencerfogelman/Downloads/CaseStudy1_2_2/Beers.csv', stringsAsFactors = FALSE)

library(dplyr)
head(breweries)
head(beers)
breweries %>% group_by(State) %>% summarise(Total = n()) 
```

Question 2

```{r}
merged = merge(x = breweries, y = beers, by.x = 'Brew_ID', by.y= 'Brewery_id', all = TRUE)
head(merged, 6)
tail(merged, 6)
```

Question 3

```{r}
for (i in 1:length(names(merged))){
  column = merged[,i]
  nas = sum(is.na(column))
  print(paste(names(merged)[i], ':', nas))
}
```


Question 4

```{r}
merged %>% group_by(State) %>% summarise(MedianAlcoholContent = median(ABV, na.rm=TRUE),
                                         MedianIBU = median(IBU, na.rm=TRUE))

```

Question 5

```{r}
maxABV = max(merged$ABV, na.rm=TRUE)
maxABV
maxIBU = max(merged$IBU, na.rm=TRUE)
maxIBU

merged %>% filter(ABV == maxABV) %>% select(State)
merged %>% filter(IBU == maxIBU) %>% select(State)
```

Question 6

```{r}
merged %>% select(ABV) %>% summary()
```


Question 7

```{r}
library(ggplot2)
ggplot(merged, aes(x=ABV, y=IBU)) + geom_point(colour = "blue", size = 0.8, na.rm = TRUE) + labs(title='Alcohol Content vs Bitterness') +
  theme(plot.title = element_text(hjust = 0.5))

```

